# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
yaw_controller:
  type: effort_controllers/JointPositionController
  joint: base_tower__nacelle
  pid: {p: 1.0, i: 1.0, d: 1.0}
blade_controller:
  type: effort_controllers/JointPositionController
  joint: nacelle__hub
  pid: {p: 1.0, i: 1.0, d: 1.0}